<option value="fa-graduation-cap" class="fa">&#xf19d</option>
<option value="fa-certificate" class="fa">&#xf0a3</option>
<option value="fa-file-text-o" class="fa">&#xf15c</option>
<option value="fa-bullhorn" class="fa">&#xf0a1</option>
<option value="fa-building-o" class="fa">&#xf1ad</option>
<option value="fa-heartbeat" class="fa">&#xf21e</option>
<option value="fa-external-link" class="fa">&#xf35d</option>
<option value="fa-flag" class="fa">&#xf024</option>
<option value="fa-university" class="fa">&#xf19c</option>
<option value="fa-users" class="fa">&#xf0c0</option>
<option value="fa-user" class="fa">&#xf007</option>
<option value="fa-check" class="fa">&#xf00c</option>
<option value="fa-trophy" class="fa">&#xf091</option>
<option value="fa-coffee" class="fa">&#xf0f4</option>
<option value="fa-file" class="fa">&#xf15b</option>
<option value="fa-clock-o" class="fa">&#xf017</option>
<option value="fa-comments" class="fa">&#xf086</option>
<option value="fa-phone" class="fa">&#xf095</option>
<option value="fa-envelope" class="fa">&#xf0e0</option>
<option value="fa-map-marker" class="fa">&#xf041</option>
